import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#FFFFFF',
        paddingBottom: 40
    },
    backButton: {
        padding: 8,
    },
    TextPage: {
        color: '#fff',
        fontWeight: '500',
        fontSize: 17,
    },
    introContainer: {
        padding: 16,
        backgroundColor: '#F7F9FA',
    },
    introText: {
        fontSize: 14,
        lineHeight: 20,
        color: '#666666',
    },
    scrollContainer: {
        flex: 1,
        padding: 16,
        paddingTop: 30,
        paddingBottom: 60,
    },
    dietCard: {
        flexDirection: 'row',
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
        borderWidth: 2,
        borderColor: 'transparent',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 5,
        elevation: 2,
    },
    selectedDietCard: {
        backgroundColor: '#F8F9FF',
        borderColor: '#35A55E',
    },
    dietCardLeft: {
        flex: 3,
        paddingRight: 12,
    },
    dietTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#333333',
        marginBottom: 8,
    },
    selectedDietTitle: {
        color: '#35A55E',
    },
    dietDescription: {
        fontSize: 14,
        color: '#666666',
        marginBottom: 12,
        lineHeight: 20,
    },
    detailButton: {
        alignSelf: 'flex-start',
        paddingVertical: 6,
    },
    detailButtonText: {
        fontSize: 14,
        color: '#35A55E',
        fontWeight: '500',
    },
    dietCardRight: {
        flex: 2,
        justifyContent: 'center',
        alignItems: 'center',
        position: 'relative',
    },
    dietImage: {
        width: 80,
        height: 80,
        borderRadius: 8,
        backgroundColor: '#f5f5f5',
    },
    checkmarkContainer: {
        position: 'absolute',
        top: -5,
        right: -5,
        backgroundColor: '#FFFFFF',
        borderRadius: 15,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 1,
    },
    saveButtonContainer: {
        padding: 16,
        borderTopWidth: 1,
        borderTopColor: '#EEEEEE',
    },
    saveButton: {
        backgroundColor: '#35A55E',
        borderRadius: 10,
        paddingVertical: 14,
        alignItems: 'center',
        justifyContent: 'center',
    },
    saveButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
    },
    detailSheet: {
        flex: 1,
        position: 'relative',
    },
    sheetHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#EEEEEE',
    },
    sheetTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#333333',
    },
    sheetContent: {
        flex: 1,
        paddingBottom: 50,
    },
    sheetScrollContent: {
        paddingBottom: 20,
    },
    sheetImage: {
        width: '100%',
        height: 180,
        borderRadius: 12,
        marginBottom: 16,
        backgroundColor: '#f5f5f5',
    },
    sheetDescriptionContainer: {
        marginBottom: 24,
    },
    sheetDescription: {
        fontSize: 15,
        lineHeight: 22,
        color: '#333333',
    },
    nutritionContainer: {
        marginBottom: 24,
    },
    macroCardContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        marginBottom: 20,
    },
    macroCard: {
        width: '48%',
        backgroundColor: '#F8F9FA',
        borderRadius: 12,
        padding: 16,
        alignItems: 'center',
        marginBottom: 12,
    },
    macroIcon: {
        width: 40,
        height: 40,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },
    macroValue: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#2C3E50',
        marginBottom: 4,
    },
    macroLabel: {
        fontSize: 12,
        color: '#666666',
        textAlign: 'center',
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333333',
        marginBottom: 12,
    },
    
    // Styles cho nguồn khuyến nghị
    sourceContainer: {
        backgroundColor: '#F0F7F4',
        borderRadius: 8,
        padding: 12,
        marginTop: 10,
        marginBottom: 100,
    },
    sourceTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: '#2C3E50',
        marginBottom: 6,
    },
    sourceLink: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    sourceLinkText: {
        fontSize: 13,
        color: '#35A55E',
        textDecorationLine: 'underline',
        flex: 1,
    },

    // Container cho nút select - fixed position
    selectButtonContainer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: 'white',
        paddingHorizontal: 20,
        paddingTop: 10,
        paddingBottom: 50,
        borderTopWidth: 1,
        borderTopColor: '#EEEEEE',
    },
    selectButton: {
        backgroundColor: '#35A55E',
        borderRadius: 12,
        paddingVertical: 16,
        alignItems: 'center',
        width: '100%',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    selectedButton: {
        backgroundColor: '#2D9150',
    },
    selectButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: '600',
    },

    // Skeleton Loading Styles
    skeletonCard: {
        flexDirection: 'row',
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
        borderWidth: 2,
        borderColor: 'transparent',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 5,
        elevation: 2,
    },
    skeletonCardLeft: {
        flex: 3,
        paddingRight: 12,
    },
    skeletonTitle: {
        height: 20,
        backgroundColor: '#E1E9EE',
        borderRadius: 4,
        marginBottom: 12,
        width: '70%',
        overflow: 'hidden',
        position: 'relative',
    },
    skeletonDescription: {
        height: 16,
        backgroundColor: '#E1E9EE',
        borderRadius: 4,
        marginBottom: 8,
        width: '90%',
        overflow: 'hidden',
        position: 'relative',
    },
    skeletonDetailButton: {
        height: 14,
        backgroundColor: '#E1E9EE',
        borderRadius: 4,
        marginTop: 8,
        width: '50%',
        overflow: 'hidden',
        position: 'relative',
    },
    skeletonCardRight: {
        flex: 2,
        justifyContent: 'center',
        alignItems: 'center',
    },
    skeletonImage: {
        width: 80,
        height: 80,
        backgroundColor: '#E1E9EE',
        borderRadius: 8,
        overflow: 'hidden',
        position: 'relative',
    },
    shimmerOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(255, 255, 255, 0.6)',
        width: 100,
    },
    buttonDisabled: {
        opacity: 0.6,
    },
});
